Vnogueira 103
getCUJO/luasocket pull request #2
Opened 2018-07-05 15:11 UTC by VictorNogueiraRio

2018-07-05 17:16 UTC, romariorios requested changes
I think you should make it clear you're fixing a problem as well

2018-07-05 17:16 UTC, romariorios commented on src/netlink.c
> +    got = got > NLMSG_SPACE(MAX_PAYLOAD) ? MAX_PAYLOAD : NLMSG_PAYLOAD(nlh, 0);
I think you should create a new variable for this value, to make it clear that this is a different thing.

2018-07-05 21:44 UTC, renatomaia requested changes

2018-07-05 21:44 UTC, renatomaia commented on src/netlink.c
> +    got = got > NLMSG_SPACE(MAX_PAYLOAD) ? MAX_PAYLOAD : NLMSG_PAYLOAD(nlh, 0);
Please fix the same thing in `receive` as well.

2018-07-09 19:09 UTC, romariorios approved these changes

2018-07-09 22:24 UTC, renatomaia approved these changes

2018-07-10 22:11 UTC, merged