RABID-584 correct memory usage in luasocket's netlink extension
getCUJO/luasocket pull request #3
Opened 2018-11-14 12:45 UTC by VictorNogueiraRio

2018-11-14 13:25 UTC, renatomaia approved these changes

2018-11-14 13:25 UTC, renatomaia commented on src/netlink.c
> +    char nlhtmp[NLMSG_SPACE(payload_size)];
I'd call this `nlbuf` or `nlmsg`, since the `char` array is the buffer to compose the full Netlink message and `nlh` is only a pointer to access the header portion of the message.

2018-11-14 14:10 UTC, ghost requested changes

2018-11-14 14:10 UTC, ghost commented on src/netlink.c
> +    char nlhtmp[NLMSG_SPACE(payload_size)];
I personally rather uint8_t than char for byte buffers, not sure about cujo's stance on this.

2018-11-14 14:10 UTC, ghost commented on src/netlink.c
> +    nlh = (struct nlmsghdr *) nlhtmp;
I would put this attribution with the definition of nlh above (unless you are going for a c89 style).

Also since this comes from a byte array, it might have a different memory alignment from the struct, and thus be miss-aligned for certain executions of the function.

Something like this should work, it does look kind of ugly tho (there might be a nicer way to do it).
```
nlh = (struct nlmsghdr *)NLMSG_ALIGN((uintptr_t)nlhtmp)
```

2018-11-14 14:10 UTC, ghost commented on src/netlink.c
> +    char nlbuf[NLMSG_SPACE(payload_size)];
I personally rather use u8 / uint8_t than char for byte buffers, not sure on cujo's stance on this.

2018-11-14 14:10 UTC, ghost commented on src/netlink.c
> +    nlh = (struct nlmsghdr *)nlbuf;
~~I would put this attribution with the definition of nlh above (unless you are going for a c89 style).~~

~~Also since this comes from a byte array, it might have a different memory alignment from the struct, and thus be miss-aligned for certain executions of the function.~~

~~Looks kind of weird but something like this should do the job (it is *UNTESTED*!)~~
```
nlh = (struct nlmsghdr *)NLMSG_ALIGN((uintptr_t)nlhtmp)
```

EDIT: reading a little more on the subject GCC guarantees 8 bytes alignment. this is unnecessary since the fields of the struct are smaller or equal than that.

2018-11-14 15:16 UTC, vfusco submitted a review, later dismissed

2018-11-14 15:16 UTC, vfusco commented on src/netlink.c
> +    nlh = (struct nlmsghdr *)nlbuf;
I'm not sure this is necessary. Can you check?

2018-11-14 15:45 UTC, mizvekov requested changes

2018-11-14 15:45 UTC, mizvekov commented on src/netlink.c
> +    char nlbuf[NLMSG_SPACE(payload_size)];
To account for proper alignment, you can do:
```
struct {
   struct nlmsghdr hdr;
   char msg[NLMSG_SPACE(MAX_PAYLOAD) - sizeof(nlmsghdr)];
} nl;
```
Also, I don't see why you would need to memset it.

2018-11-14 15:45 UTC, mizvekov commented on src/netlink.c
> +    nlh = (struct nlmsghdr *)nlbuf;
See suggestion above

2018-11-14 17:11 UTC, mizvekov requested changes

2018-11-14 17:11 UTC, mizvekov commented on src/netlink.c
> +    nlh = (struct nlmsghdr *)nlbuf;
There is no guarantee char arrays allocated on the stack have any particular alignment, the code is still wrong.
uint8_t is misplaced here, we are just using the array for copy / casting, and other places in this file as using char for the same purpose.
Using char is fine, and is the most common idiom.

2018-11-14 17:17 UTC, VictorNogueiraRio commented on src/netlink.c
> +    nlh = (struct nlmsghdr *)nlbuf;
Sorry, about that. I pushed this fixup right after you did your review, so i ended up not seeing it before i pushed. Will do another fixup correcting that

2018-11-14 18:37 UTC, ghost submitted a review, later dismissed

2018-11-16 16:48 UTC, renatomaia submitted a review, later dismissed

2018-11-16 16:54 UTC, mizvekov submitted a review, later dismissed

2018-11-19 17:08 UTC, renatomaia approved these changes

2018-11-19 17:15 UTC, mizvekov approved these changes

2018-11-19 18:27 UTC, vfusco approved these changes

2018-11-19 18:29 UTC, merged